### ISSUE TITLE
Add async `check` helper

### ISSUE THREAD

**Issue by inancgumus** [grafana/jslib.k6.io#125]
# What

Add a helper that supports asynchronous `check` functionality.

Example (currently, it does not work):

```javascript
check(page, {
    'checked': async p => await p.locator('.checked').isChecked(),
});
```

We use the following code until we add async `check` support:

```javascript
const isChecked = await p.locator('.checked').isChecked();
check(page, {
    'checked': p => isChecked,
});
```

# Why

We're converting the browser's [sync methods to async](https://github.com/grafana/xk6-browser/issues/428). We noticed that `check` intentionally [does not allow](https://github.com/grafana/k6/issues/2728#issuecomment-1404747660) async methods in it. This issue isn't great for user experience (also considering the browser's 150ish methods will be async). Can we find a way to make this more user-friendly?

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/k6-jslib-utils/pull/13
- [x] Upload the library
- [ ] https://github.com/grafana/k6-docs/issues/1725
- [x] k6: Add it to release notes
```

**Comment by inancgumus** [comment]
Hey, @allansson, since you started working on this, I've assigned this issue to you. Let me know if it's OK. Thanks!

**Comment by inancgumus** [comment]
Updating k6-docs will be tackled in another issue: grafana/k6-docs#1725
